### ISSUE TITLE
Yale Locks

### ISSUE THREAD

**Issue by lindehoff** [persandstrom/python-verisure#3]
Any chance off supporting Yale doorman?

**Comment by persandstrom** [comment]
I don't have the locks myself so it will be hard for me to try to reverse engineer it. I guess they don't have an open API.

**Comment by lindehoff** [comment]
I do not either but I got an inquiry from a user using the plugin. I will try to examine it more to see if he can control the lock through MyPages. If so, it's should be solvable.

**Comment by persandstrom** [comment]
Hope it is. 

Fun to hear that my script is used :)

**Comment by lindehoff** [comment]
It's very useful, thank you very much.
I was poking around MyPage and found `/remotecontrol/lockunlock.cmd`it seems to be a possible API for locks. But I think it will be very difficult to reverse engineer without a lock.

**Comment by HebronNor** [comment]
I have the lock. How can I help?

**Comment by lindehoff** [comment]
@HebronNor Do you get any information about the lock status when you go to https://mypages.verisure.com/remotecontrol
You have to be logged in.

**Comment by HebronNor** [comment]
Yes;

    {
    "date":"I dag 09:02",
    "notAllowedReason":"",
    "image":"locked",
    "name":"",
    "operational":true,
    "location":"xXx",
    "changeAllowed":true,
    "id":"xXx",
    "label":"Låst",
    "type":"DOOR_LOCK",
    "secureMode":false,
    "status":"locked"
    }

Haven't had time to check the different POST commands yet, will do it this evening.

**Comment by HebronNor** [comment]
@persandstrom Here it is...

Lock:

    code=xXx&deviceLabel=xXx&state=LOCKED&_csrf=xXx

Unlock:

    code=xXx&deviceLabel=xXx&state=UNLOCKED&_csrf=xXx

Need anything else?

**Comment by persandstrom** [comment]
That should be enough, thanks. Maybe you can test it when I'm done?

**Comment by HebronNor** [comment]
Of cource, let me know :)

**Comment by persandstrom** [comment]
I have added commands for locks now. 
could you please see if it works @HebronNor 

Tell me if there is something that does not have the right "feel" as well. It is hard to know when I can't try it.

**Comment by HebronNor** [comment]
@persandstrom Sure :) I'll get it done tonight or tomorrow night.

**Comment by HebronNor** [comment]
I am getting duplicate entries for alarm and lock, when I type `get lock` or `get alarm`:

```
alarm
        name: Thomas Jensen
        operational: True
        id: xXx
        notAllowedReason:
        image: unlocked
        location: xXx
        type: DOOR_LOCK
        label: Unlocked
        changeAllowed: True
        secureMode: False
        status: unlocked
        date: Today 6:57 PM
alarm
        name: Thomas Jensen
        id: 1
        notAllowedReason:
        type: ARM_STATE
        label: Disarmed
        changeAllowed: True
        status: unarmed
        date: Today 6:57 PM

lock                                 
        operational: True            
        id: xXx                 
        changeAllowed: True          
        date: Today 6:57 PM          
        name: Thomas Jensen          
        notAllowedReason:            
        status: unlocked             
        location: xXx           
        label: Unlocked              
        image: unlocked              
        type: DOOR_LOCK              
        secureMode: False            
lock                                 
        id: 1                        
        changeAllowed: True          
        date: Today 6:57 PM          
        name: Thomas Jensen          
        notAllowedReason:            
        status: unarmed              
        label: Disarmed              
        type: ARM_STATE              
```

Haven't tried to lock it yet, as I fear I also might arm the alarm and the kids are sleeping... :-p
